version: ~> 1.0

language: cpp

cache:
  directories:
    - ${QT_INSTALL_DIR}
    - ~/.ccache

git:
  submodules: false

env:
  global:
    - QBS_INSTALL_DIR=${TRAVIS_BUILD_DIR}/qbs
    - QBS_TEST_SOURCE_ROOT="${TRAVIS_BUILD_DIR}/tests"
    - QT_INSTALL_DIR=~/Qt
    - QT_VERSION=5.12.7
    - QTCREATOR_VERSION=4.10.2
    - PATH="${QBS_INSTALL_DIR}/bin:${PATH}"


stages:
  - name: Build
  - name: Test

import:
  - source: ci/travis-macos-stages.yml
  - source: ci/travis-linux-stages.yml
  - source: ci/travis-windows-stages.yml
