version: "3.7"

x-default-service: &linux
  working_dir: /qbs
  environment:
    - BUILD_OPTIONS
    - QTEST_FUNCTION_TIMEOUT
    - QBS_AUTOTEST_PROFILE
    - QBS_TEST_SOURCE_ROOT
    - WITH_ARCHIVE
    - WITH_TESTS
  volumes:
    - .:/qbs
    - ~/.ccache:/home/devel/.ccache
  network_mode: bridge
  cap_add:
      - SYS_PTRACE

services:
  focal:
    << : *linux
    hostname: focal
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-5.15.0_1.15.1-0
    build:
      dockerfile: docker/focal/Dockerfile
      context: .
      args:
        QT_VERSION: 5.15.0
        QTCREATOR_VERSION: 4.11.2

  focal-android-513:
    << : *linux
    hostname: focal-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-android-5.13.2-0
    build:
      dockerfile: docker/focal/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.13.2

  focal-android-514:
    << : *linux
    hostname: focal-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-android-5.14.0-0
    build:
      dockerfile: docker/focal/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.14.0

  focal-android-515:
    << : *linux
    hostname: focal-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-android-5.15.1-0
    build:
      dockerfile: docker/focal/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.15.1

  focal-baremetal:
    << : *linux
    hostname: focal-baremetal
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-baremetal-2
    build:
      dockerfile: docker/focal/test-baremetal.Dockerfile
      context: .

  windows:
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:windowsservercore-5.15.0_1.16.0-0
    build:
      dockerfile: docker/windowsservercore/Dockerfile
      context: .
      args:
        QT_VERSION: 5.15.0
        QBS_VERSION: 1.16.0
    working_dir: 'C:/qbs'
    environment:
      - BUILD_OPTIONS
      - WITH_DOCS
    volumes:
      - type: bind
        source: .
        target: C:\qbs
      - type: bind
        source: ~/.ccache
        target: C:\.ccache
    network_mode: nat
