###############################################################################
# Common nodes
###############################################################################

###############################################################################
# Begin of pipeline
###############################################################################

env:
  global:
    - CLCACHE_DIR=${HOME}/.ccache

jobs:
  include:

###############################################################################
# Build stage
###############################################################################

    - &build-on-windows
      stage: Build
      name: With Qbs on Windows (Visual Studio 2017)
      os: windows
      env:
        - &build-on-windows_environment |
          PATH="${QT_INSTALL_DIR}/Tools/QtCreator/bin:/c/Python38:/c/Python39:/c/Python38/Scripts:/c/Python39/Scripts:${PATH}"
          QT_VERSION=5.12.6
          QTCREATOR_VERSION=4.10.2
          QMAKE_PATH=${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017_64/bin/qmake.exe
      before_install:
        # Install Qbs and Qt
        - ./scripts/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win64_msvc2017_64 qtbase qtdeclarative qttools qtscript
        - ./scripts/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QTCREATOR_VERSION} qtcreator
        - choco install python3
        - pip3 install git+https://github.com/frerich/clcache.git@cae73d8255d78db8ba11e23c51fd2c9a89e7475b
        - pip3 install conan beautifulsoup4 lxml
      before_script:
        - clcache -s
      after_script:
        - clcache -s
      script:
        - qbs setup-toolchains --detect
        - qbs setup-qt ${QMAKE_PATH} qt
        - qbs config qt.baseProfile MSVC2017-x64
        - qbs config defaultProfile qt
        - >
          qbs build
          profile:qt
          config:release
          modules.cpp.compilerWrapper:clcache
          modules.qbs.installRoot:"${QBS_INSTALL_DIR/\/c/C:}"
          modules.qbsbuildconfig.enableBundledQt:true
          modules.qbsbuildconfig.enableProjectFileUpdates:true
          modules.qbsbuildconfig.enableUnitTests:true
          modules.cpp.treatWarningsAsErrors:true
          project.withDocumentation:false
      workspaces:
        create:
          name: build_windows_msvc2017
          paths: ${QBS_INSTALL_DIR}

    - <<: *build-on-windows
      if: branch = master
      name: With Qbs on Windows (clang-cl)
      script:
        - qbs setup-toolchains --detect
        - qbs setup-qt ${QMAKE_PATH} qt
        - qbs config profiles.qt.baseProfile clang-cl-x86_64
        - qbs config defaultProfile qt
        - >
          qbs build
          profile:qt
          config:release
          modules.cpp.compilerWrapper:clcache
          modules.qbs.installRoot:"${QBS_INSTALL_DIR/\/c/C:}"
          modules.qbsbuildconfig.enableAddressSanitizer:false
          modules.qbsbuildconfig.enableBundledQt:true
          modules.qbsbuildconfig.enableProjectFileUpdates:true
          modules.qbsbuildconfig.enableUnitTests:true
          modules.cpp.treatWarningsAsErrors:true
          project.withDocumentation:false

    - &build-on-windows-with-docker
      stage: Build Qbs and and run autotests
      name: With Qbs on Windows with Docker (Visual Studio 2017)
      if: branch = master
      os: windows
      services: docker
      before-install:
        - curl -sLo "/c/Program Files/Docker/docker-compose.exe" https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Windows-x86_64.exe
        - docker-compose pull windows
      before_script:
        - docker-compose run --rm windows clcache -s
      script:
        - >
          docker-compose run --rm windows qbs build
          -p dist
          qbs.buildVariant:release
          modules.cpp.compilerWrapper:clcache
          modules.qbs.installRoot:"${QBS_INSTALL_DIR/${TRAVIS_BUILD_DIR}/C:/qbs}"
          modules.qbsbuildconfig.enableBundledQt:true
          modules.qbsbuildconfig.enableProjectFileUpdates:true
          modules.qbsbuildconfig.enableUnitTests:true
          modules.cpp.treatWarningsAsErrors:true
          project.withDocumentation:true
          project.withExamples:true
          config:release-64 profile:qt64
          config:release profile:qt
      after_script:
        - docker-compose run --rm windows clcache -s


###############################################################################
# Test stage
###############################################################################

###### Basic ######
    - &test_on_windows
      stage: Test
      name: api, language, buildgraph, cmdlineparser, tools, blackbox-joblimits
      os: windows
      env: &test_on_windows-env
        QBS_AUTOTEST_PROFILE=MSVC2017-x64
      workspaces:
        use:
          - build_windows_msvc2017
      before_script:
        - &test_on_windows-before_script |
          qbs setup-toolchains --detect
          qbs config --list
        - ./scripts/install-qt.sh -d ~/Qt --version 5.12.7 --toolchain win64_msvc2017_64 qtbase
        - qbs setup-qt ~/Qt/5.12.7/msvc2017_64/bin/qmake.exe qt
        - qbs config qt.baseProfile ${QBS_AUTOTEST_PROFILE}
        - qbs config --list
      script:
        - QBS_AUTOTEST_PROFILE=qt tst_api
        - tst_language
        - tst_buildgraph
        - tst_cmdlineparser
        - tst_tools
        - tst_blackbox-joblimits

    - <<: *test_on_windows
      name: blackbox
      script:
        - tst_blackbox

###### Qt ######

    - &test_on_windows-qt
      <<: *test_on_windows
      name: blackbox-qt (5.12.7)
      env:
        - *test_on_windows-env
        - QT_VERSION=5.12.7
        - &test_on_windows-qt-env |
          QMAKE_PATH=${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017_64/bin/qmake.exe
          QBS_AUTOTEST_PROFILE=qt
      before_install:
        - ./scripts/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win64_msvc2017_64 qtbase qtdeclarative qttools qtscript qtscxml
      before_script:
        - *test_on_windows-before_script
        - qbs setup-qt ${QMAKE_PATH} qt
        - qbs config --list
      script:
        - tst_blackbox-qt

    - <<: *test_on_windows-qt
      name: blackbox-qt (5.14.1)
      env:
        - *test_on_windows-env
        - QT_VERSION=5.14.1
        - *test_on_windows-qt-env

    - <<: *test_on_windows-qt
      name: blackbox-qt (5.15.0)
      env:
        - *test_on_windows-env
        - QT_VERSION=5.15.0
        - *test_on_windows-qt-env
